[2024-10-20T21:05:48.037+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-20T21:05:48.051+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: email_example.sending_email_example manual__2024-10-20T14:05:23.292078+00:00 [queued]>
[2024-10-20T21:05:48.061+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: email_example.sending_email_example manual__2024-10-20T14:05:23.292078+00:00 [queued]>
[2024-10-20T21:05:48.061+0700] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-20T21:05:48.077+0700] {taskinstance.py:2888} INFO - Executing <Task(EmailOperator): sending_email_example> on 2024-10-20 14:05:23.292078+00:00
[2024-10-20T21:05:48.089+0700] {standard_task_runner.py:72} INFO - Started process 26202 to run task
[2024-10-20T21:05:48.106+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'email_example', 'sending_email_example', 'manual__2024-10-20T14:05:23.292078+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/var/folders/3z/w6kw66r93jxd4b5xvgpxfbkm0000gn/T/tmpa6ucsss1']
[2024-10-20T21:05:48.109+0700] {standard_task_runner.py:105} INFO - Job 3: Subtask sending_email_example
[2024-10-20T21:05:48.310+0700] {task_command.py:467} INFO - Running <TaskInstance: email_example.sending_email_example manual__2024-10-20T14:05:23.292078+00:00 [running]> on host macbook-pro-khxng-krissanapong.local
[2024-10-20T21:05:48.398+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='email_example' AIRFLOW_CTX_TASK_ID='sending_email_example' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T14:05:23.292078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-20T14:05:23.292078+00:00'
[2024-10-20T21:05:48.400+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-20T21:05:48.400+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-20T21:05:48.401+0700] {logging_mixin.py:190} INFO - Current task name:sending_email_example state:running start_date:2024-10-20 14:05:48.051778+00:00
[2024-10-20T21:05:48.402+0700] {logging_mixin.py:190} INFO - Dag name:email_example and current dag run status:running
[2024-10-20T21:05:48.402+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-20T21:05:48.421+0700] {logging_mixin.py:190} WARNING - /Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py:155 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-10-20T21:05:48.422+0700] {email.py:272} INFO - Email alerting: attempt 1
[2024-10-20T21:05:55.026+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [KL1PR0401CA0004.apcprd04.prod.outlook.com 2024-10-20T14:05:55.232Z 08DCF0E8DA8DF0D7]')
[2024-10-20T21:05:55.043+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-20T21:05:55.044+0700] {logging_mixin.py:190} INFO - Task start:2024-10-20 14:05:48.051778+00:00 end:2024-10-20 14:05:55.042401+00:00 duration:6.990623
[2024-10-20T21:05:55.044+0700] {logging_mixin.py:190} INFO - Task:<Task(EmailOperator): sending_email_example> dag:<DAG: email_example> dagrun:<DagRun email_example @ 2024-10-20 14:05:23.292078+00:00: manual__2024-10-20T14:05:23.292078+00:00, state:running, queued_at: 2024-10-20 14:05:23.358539+00:00. externally triggered: True>
[2024-10-20T21:05:55.045+0700] {logging_mixin.py:190} INFO - Failure caused by (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [KL1PR0401CA0004.apcprd04.prod.outlook.com 2024-10-20T14:05:55.232Z 08DCF0E8DA8DF0D7]')
[2024-10-20T21:05:55.046+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=email_example, task_id=sending_email_example, run_id=manual__2024-10-20T14:05:23.292078+00:00, execution_date=20241020T140523, start_date=20241020T140548, end_date=20241020T140555
[2024-10-20T21:05:55.063+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-20T21:05:55.064+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task sending_email_example ((535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [KL1PR0401CA0004.apcprd04.prod.outlook.com 2024-10-20T14:05:55.232Z 08DCF0E8DA8DF0D7]'); 26202)
Traceback (most recent call last):
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 155, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.139 Authentication unsuccessful, basic authentication is disabled. [KL1PR0401CA0004.apcprd04.prod.outlook.com 2024-10-20T14:05:55.232Z 08DCF0E8DA8DF0D7]')
[2024-10-20T21:05:55.078+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-20T21:05:55.107+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-20T21:05:55.107+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
